name: Test and build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Npm audit
        run: |
          npm config set audit-level critical
          npm audit --registry="https://registry.npmjs.org"

  test:
    runs-on: ubuntu-latest
    needs: [audit]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install npm dependencies
        run: npm ci
      - name: Run unit tests
        run: npm test

  build:
    runs-on: ubuntu-latest
    needs: [audit]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Node
        uses: actions/setup-node@v3
      - uses: actions/cache@v3
        id: npm-cache
        with:
          path: ~/.npm
          key: npm-${{ hashFiles('**/package-lock.json') }}
      - name: Install npm dependencies
        run: npm ci
      - name: Build app
        run: npm run build --if-present
